### ISSUE TITLE
[Task 4] Implement a simple "Popup"

### ISSUE THREAD

**Issue by odeadglaz** [omriu/shavzakist#1]
Implement a Popup in the following scenario:

1. There is a button on the page with the text "Show"
2. The Popup is shown when the user clicks on the button.
3. There is a black screen, and in the center, there is a white `<div>` with the text -> "Omri Uliel".
4. If the user clicks on the black screen, The popup closes.
5. If the user clicks on the white box, nothing happens.

**Comment by omriu** [comment]
hay.
i waiting for Another task for me
